// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shellmock

import (
	"context"
	"time"

	"github.com/slok/gosimov/pkg/tool/shell"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExecutor creates a new instance of MockExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExecutor {
	mock := &MockExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExecutor is an autogenerated mock type for the Executor type
type MockExecutor struct {
	mock.Mock
}

type MockExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExecutor) EXPECT() *MockExecutor_Expecter {
	return &MockExecutor_Expecter{mock: &_m.Mock}
}

// Exec provides a mock function for the type MockExecutor
func (_mock *MockExecutor) Exec(ctx context.Context, command string, cwd string, timeout time.Duration) (*shell.Result, error) {
	ret := _mock.Called(ctx, command, cwd, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 *shell.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (*shell.Result, error)); ok {
		return returnFunc(ctx, command, cwd, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) *shell.Result); ok {
		r0 = returnFunc(ctx, command, cwd, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*shell.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, command, cwd, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExecutor_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type MockExecutor_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - command string
//   - cwd string
//   - timeout time.Duration
func (_e *MockExecutor_Expecter) Exec(ctx interface{}, command interface{}, cwd interface{}, timeout interface{}) *MockExecutor_Exec_Call {
	return &MockExecutor_Exec_Call{Call: _e.mock.On("Exec", ctx, command, cwd, timeout)}
}

func (_c *MockExecutor_Exec_Call) Run(run func(ctx context.Context, command string, cwd string, timeout time.Duration)) *MockExecutor_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockExecutor_Exec_Call) Return(result *shell.Result, err error) *MockExecutor_Exec_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockExecutor_Exec_Call) RunAndReturn(run func(ctx context.Context, command string, cwd string, timeout time.Duration) (*shell.Result, error)) *MockExecutor_Exec_Call {
	_c.Call.Return(run)
	return _c
}
