version: "2"
linters:
  enable:
    - godot
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
formatters:
  enable:
    - gofmt
    - goimports
