// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package toolmock

import (
	"context"
	"encoding/json"

	"github.com/slok/gosimov/pkg/tool"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTool creates a new instance of MockTool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTool {
	mock := &MockTool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTool is an autogenerated mock type for the Tool type
type MockTool struct {
	mock.Mock
}

type MockTool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTool) EXPECT() *MockTool_Expecter {
	return &MockTool_Expecter{mock: &_m.Mock}
}

// Description provides a mock function for the type MockTool
func (_mock *MockTool) Description() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTool_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockTool_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockTool_Expecter) Description() *MockTool_Description_Call {
	return &MockTool_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockTool_Description_Call) Run(run func()) *MockTool_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_Description_Call) Return(s string) *MockTool_Description_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTool_Description_Call) RunAndReturn(run func() string) *MockTool_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Execute provides a mock function for the type MockTool
func (_mock *MockTool) Execute(ctx context.Context, args json.RawMessage) (*tool.Result, error) {
	ret := _mock.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *tool.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, json.RawMessage) (*tool.Result, error)); ok {
		return returnFunc(ctx, args)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, json.RawMessage) *tool.Result); ok {
		r0 = returnFunc(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tool.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, args)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTool_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTool_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - args json.RawMessage
func (_e *MockTool_Expecter) Execute(ctx interface{}, args interface{}) *MockTool_Execute_Call {
	return &MockTool_Execute_Call{Call: _e.mock.On("Execute", ctx, args)}
}

func (_c *MockTool_Execute_Call) Run(run func(ctx context.Context, args json.RawMessage)) *MockTool_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTool_Execute_Call) Return(result *tool.Result, err error) *MockTool_Execute_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockTool_Execute_Call) RunAndReturn(run func(ctx context.Context, args json.RawMessage) (*tool.Result, error)) *MockTool_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockTool
func (_mock *MockTool) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTool_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTool_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTool_Expecter) ID() *MockTool_ID_Call {
	return &MockTool_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTool_ID_Call) Run(run func()) *MockTool_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_ID_Call) Return(s string) *MockTool_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTool_ID_Call) RunAndReturn(run func() string) *MockTool_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Schema provides a mock function for the type MockTool
func (_mock *MockTool) Schema() json.RawMessage {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Schema")
	}

	var r0 json.RawMessage
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	return r0
}

// MockTool_Schema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Schema'
type MockTool_Schema_Call struct {
	*mock.Call
}

// Schema is a helper method to define mock.On call
func (_e *MockTool_Expecter) Schema() *MockTool_Schema_Call {
	return &MockTool_Schema_Call{Call: _e.mock.On("Schema")}
}

func (_c *MockTool_Schema_Call) Run(run func()) *MockTool_Schema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTool_Schema_Call) Return(rawMessage json.RawMessage) *MockTool_Schema_Call {
	_c.Call.Return(rawMessage)
	return _c
}

func (_c *MockTool_Schema_Call) RunAndReturn(run func() json.RawMessage) *MockTool_Schema_Call {
	_c.Call.Return(run)
	return _c
}
