// Code generated by pkg/llm/internal/cmd/genmodels. DO NOT EDIT.
// Source: https://models.dev/api.json

package zen

import "github.com/slok/gosimov/pkg/model"

const (
	ModelBigPickle               = "big-pickle"
	ModelDeepseekV4FlashFree     = "deepseek-v4-flash-free"
	ModelGemini3Flash            = "gemini-3-flash"
	ModelGemini3Pro              = "gemini-3-pro"
	ModelGemini31Pro             = "gemini-3.1-pro"
	ModelGlm46                   = "glm-4.6"
	ModelGlm47                   = "glm-4.7"
	ModelGlm47Free               = "glm-4.7-free"
	ModelGlm5                    = "glm-5"
	ModelGlm5Free                = "glm-5-free"
	ModelGlm51                   = "glm-5.1"
	ModelGpt5                    = "gpt-5"
	ModelGpt5Codex               = "gpt-5-codex"
	ModelGpt5Nano                = "gpt-5-nano"
	ModelGpt51                   = "gpt-5.1"
	ModelGpt51Codex              = "gpt-5.1-codex"
	ModelGpt51CodexMax           = "gpt-5.1-codex-max"
	ModelGpt51CodexMini          = "gpt-5.1-codex-mini"
	ModelGpt52                   = "gpt-5.2"
	ModelGpt52Codex              = "gpt-5.2-codex"
	ModelGpt53Codex              = "gpt-5.3-codex"
	ModelGpt53CodexSpark         = "gpt-5.3-codex-spark"
	ModelGpt54                   = "gpt-5.4"
	ModelGpt54Mini               = "gpt-5.4-mini"
	ModelGpt54Nano               = "gpt-5.4-nano"
	ModelGpt54Pro                = "gpt-5.4-pro"
	ModelGpt55                   = "gpt-5.5"
	ModelGpt55Pro                = "gpt-5.5-pro"
	ModelGrokCode                = "grok-code"
	ModelHy3PreviewFree          = "hy3-preview-free"
	ModelKimiK2                  = "kimi-k2"
	ModelKimiK2Thinking          = "kimi-k2-thinking"
	ModelKimiK25                 = "kimi-k2.5"
	ModelKimiK25Free             = "kimi-k2.5-free"
	ModelKimiK26                 = "kimi-k2.6"
	ModelLing26FlashFree         = "ling-2.6-flash-free"
	ModelMimoV2FlashFree         = "mimo-v2-flash-free"
	ModelMimoV2OmniFree          = "mimo-v2-omni-free"
	ModelMimoV2ProFree           = "mimo-v2-pro-free"
	ModelMinimaxM21              = "minimax-m2.1"
	ModelMinimaxM21Free          = "minimax-m2.1-free"
	ModelMinimaxM27              = "minimax-m2.7"
	ModelNemotron3SuperFree      = "nemotron-3-super-free"
	ModelQwen3Coder              = "qwen3-coder"
	ModelQwen35Plus              = "qwen3.5-plus"
	ModelQwen36Plus              = "qwen3.6-plus"
	ModelQwen36PlusFree          = "qwen3.6-plus-free"
	ModelRing261tFree            = "ring-2.6-1t-free"
	ModelTrinityLargePreviewFree = "trinity-large-preview-free"
)

var modelIDs = []string{
	"big-pickle",
	"deepseek-v4-flash-free",
	"gemini-3-flash",
	"gemini-3-pro",
	"gemini-3.1-pro",
	"glm-4.6",
	"glm-4.7",
	"glm-4.7-free",
	"glm-5",
	"glm-5-free",
	"glm-5.1",
	"gpt-5",
	"gpt-5-codex",
	"gpt-5-nano",
	"gpt-5.1",
	"gpt-5.1-codex",
	"gpt-5.1-codex-max",
	"gpt-5.1-codex-mini",
	"gpt-5.2",
	"gpt-5.2-codex",
	"gpt-5.3-codex",
	"gpt-5.3-codex-spark",
	"gpt-5.4",
	"gpt-5.4-mini",
	"gpt-5.4-nano",
	"gpt-5.4-pro",
	"gpt-5.5",
	"gpt-5.5-pro",
	"grok-code",
	"hy3-preview-free",
	"kimi-k2",
	"kimi-k2-thinking",
	"kimi-k2.5",
	"kimi-k2.5-free",
	"kimi-k2.6",
	"ling-2.6-flash-free",
	"mimo-v2-flash-free",
	"mimo-v2-omni-free",
	"mimo-v2-pro-free",
	"minimax-m2.1",
	"minimax-m2.1-free",
	"minimax-m2.7",
	"nemotron-3-super-free",
	"qwen3-coder",
	"qwen3.5-plus",
	"qwen3.6-plus",
	"qwen3.6-plus-free",
	"ring-2.6-1t-free",
	"trinity-large-preview-free",
}

var modelsByID = map[string]model.LLMModelInfo{
	"big-pickle": {
		ID:               "big-pickle",
		Name:             "Big Pickle",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"deepseek-v4-flash-free": {
		ID:               "deepseek-v4-flash-free",
		Name:             "DeepSeek V4 Flash Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gemini-3-flash": {
		ID:               "gemini-3-flash",
		Name:             "Gemini 3 Flash",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gemini-3-pro": {
		ID:               "gemini-3-pro",
		Name:             "Gemini 3 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gemini-3.1-pro": {
		ID:               "gemini-3.1-pro",
		Name:             "Gemini 3.1 Pro Preview",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-4.6": {
		ID:               "glm-4.6",
		Name:             "GLM-4.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-4.7": {
		ID:               "glm-4.7",
		Name:             "GLM-4.7",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-4.7-free": {
		ID:               "glm-4.7-free",
		Name:             "GLM-4.7 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5": {
		ID:               "glm-5",
		Name:             "GLM-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5-free": {
		ID:               "glm-5-free",
		Name:             "GLM-5 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5.1": {
		ID:               "glm-5.1",
		Name:             "GLM-5.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5": {
		ID:               "gpt-5",
		Name:             "GPT-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-codex": {
		ID:               "gpt-5-codex",
		Name:             "GPT-5 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-nano": {
		ID:               "gpt-5-nano",
		Name:             "GPT-5 Nano",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1": {
		ID:               "gpt-5.1",
		Name:             "GPT-5.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex": {
		ID:               "gpt-5.1-codex",
		Name:             "GPT-5.1 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-max": {
		ID:               "gpt-5.1-codex-max",
		Name:             "GPT-5.1 Codex Max",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-mini": {
		ID:               "gpt-5.1-codex-mini",
		Name:             "GPT-5.1 Codex Mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2": {
		ID:               "gpt-5.2",
		Name:             "GPT-5.2",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2-codex": {
		ID:               "gpt-5.2-codex",
		Name:             "GPT-5.2 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex": {
		ID:               "gpt-5.3-codex",
		Name:             "GPT-5.3 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex-spark": {
		ID:               "gpt-5.3-codex-spark",
		Name:             "GPT-5.3 Codex Spark",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4": {
		ID:               "gpt-5.4",
		Name:             "GPT-5.4",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4-mini": {
		ID:               "gpt-5.4-mini",
		Name:             "GPT-5.4 Mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4-nano": {
		ID:               "gpt-5.4-nano",
		Name:             "GPT-5.4 Nano",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4-pro": {
		ID:               "gpt-5.4-pro",
		Name:             "GPT-5.4 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.5": {
		ID:               "gpt-5.5",
		Name:             "GPT-5.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.5-pro": {
		ID:               "gpt-5.5-pro",
		Name:             "GPT-5.5 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"grok-code": {
		ID:               "grok-code",
		Name:             "Grok Code Fast 1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    256000,
		MaxOutputTokens:  256000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"hy3-preview-free": {
		ID:               "hy3-preview-free",
		Name:             "Hy3 preview Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    256000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2": {
		ID:               "kimi-k2",
		Name:             "Kimi K2",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  262144,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2-thinking": {
		ID:               "kimi-k2-thinking",
		Name:             "Kimi K2 Thinking",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  262144,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.5": {
		ID:               "kimi-k2.5",
		Name:             "Kimi K2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.5-free": {
		ID:               "kimi-k2.5-free",
		Name:             "Kimi K2.5 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  262144,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.6": {
		ID:               "kimi-k2.6",
		Name:             "Kimi K2.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"ling-2.6-flash-free": {
		ID:               "ling-2.6-flash-free",
		Name:             "Ling 2.6 Flash Free",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    262100,
		MaxOutputTokens:  32800,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2-flash-free": {
		ID:               "mimo-v2-flash-free",
		Name:             "MiMo V2 Flash Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2-omni-free": {
		ID:               "mimo-v2-omni-free",
		Name:             "MiMo V2 Omni Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2-pro-free": {
		ID:               "mimo-v2-pro-free",
		Name:             "MiMo V2 Pro Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.1": {
		ID:               "minimax-m2.1",
		Name:             "MiniMax M2.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.1-free": {
		ID:               "minimax-m2.1-free",
		Name:             "MiniMax M2.1 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.7": {
		ID:               "minimax-m2.7",
		Name:             "MiniMax M2.7",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"nemotron-3-super-free": {
		ID:               "nemotron-3-super-free",
		Name:             "Nemotron 3 Super Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3-coder": {
		ID:               "qwen3-coder",
		Name:             "Qwen3 Coder",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3.5-plus": {
		ID:               "qwen3.5-plus",
		Name:             "Qwen3.5 Plus",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3.6-plus": {
		ID:               "qwen3.6-plus",
		Name:             "Qwen3.6 Plus",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3.6-plus-free": {
		ID:               "qwen3.6-plus-free",
		Name:             "Qwen3.6 Plus Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"ring-2.6-1t-free": {
		ID:               "ring-2.6-1t-free",
		Name:             "Ring 2.6 1T Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262000,
		MaxOutputTokens:  66000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"trinity-large-preview-free": {
		ID:               "trinity-large-preview-free",
		Name:             "Trinity Large Preview",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    131072,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

// IsSupportedModel returns true if model ID exists in the Zen catalog.
func IsSupportedModel(modelID string) bool {
	_, ok := modelsByID[modelID]
	return ok
}

// ModelByID returns model metadata when present.
func ModelByID(modelID string) (model.LLMModelInfo, bool) {
	v, ok := modelsByID[modelID]
	return v, ok
}

// SupportedModelIDs returns all known Zen model IDs.
func SupportedModelIDs() []string {
	ids := make([]string, len(modelIDs))
	copy(ids, modelIDs)
	return ids
}
