// Code generated by pkg/llm/internal/cmd/genmodels. DO NOT EDIT.
// Source: https://models.dev/api.json

package zen

import "github.com/slok/gosimov/pkg/model"

const (
	ModelBigPickle               = "big-pickle"
	ModelClaude35Haiku           = "claude-3-5-haiku"
	ModelClaudeHaiku45           = "claude-haiku-4-5"
	ModelClaudeOpus41            = "claude-opus-4-1"
	ModelClaudeOpus45            = "claude-opus-4-5"
	ModelClaudeOpus46            = "claude-opus-4-6"
	ModelClaudeSonnet4           = "claude-sonnet-4"
	ModelClaudeSonnet45          = "claude-sonnet-4-5"
	ModelClaudeSonnet46          = "claude-sonnet-4-6"
	ModelGemini3Flash            = "gemini-3-flash"
	ModelGemini3Pro              = "gemini-3-pro"
	ModelGemini31Pro             = "gemini-3.1-pro"
	ModelGlm46                   = "glm-4.6"
	ModelGlm47                   = "glm-4.7"
	ModelGlm47Free               = "glm-4.7-free"
	ModelGlm5                    = "glm-5"
	ModelGlm5Free                = "glm-5-free"
	ModelGpt5                    = "gpt-5"
	ModelGpt5Codex               = "gpt-5-codex"
	ModelGpt5Nano                = "gpt-5-nano"
	ModelGpt51                   = "gpt-5.1"
	ModelGpt51Codex              = "gpt-5.1-codex"
	ModelGpt51CodexMax           = "gpt-5.1-codex-max"
	ModelGpt51CodexMini          = "gpt-5.1-codex-mini"
	ModelGpt52                   = "gpt-5.2"
	ModelGpt52Codex              = "gpt-5.2-codex"
	ModelGpt53Codex              = "gpt-5.3-codex"
	ModelGpt53CodexSpark         = "gpt-5.3-codex-spark"
	ModelGpt54                   = "gpt-5.4"
	ModelGpt54Pro                = "gpt-5.4-pro"
	ModelGrokCode                = "grok-code"
	ModelKimiK2                  = "kimi-k2"
	ModelKimiK2Thinking          = "kimi-k2-thinking"
	ModelKimiK25                 = "kimi-k2.5"
	ModelKimiK25Free             = "kimi-k2.5-free"
	ModelMinimaxM21              = "minimax-m2.1"
	ModelMinimaxM21Free          = "minimax-m2.1-free"
	ModelMinimaxM25              = "minimax-m2.5"
	ModelMinimaxM25Free          = "minimax-m2.5-free"
	ModelQwen3Coder              = "qwen3-coder"
	ModelTrinityLargePreviewFree = "trinity-large-preview-free"
)

var modelIDs = []string{
	"big-pickle",
	"claude-3-5-haiku",
	"claude-haiku-4-5",
	"claude-opus-4-1",
	"claude-opus-4-5",
	"claude-opus-4-6",
	"claude-sonnet-4",
	"claude-sonnet-4-5",
	"claude-sonnet-4-6",
	"gemini-3-flash",
	"gemini-3-pro",
	"gemini-3.1-pro",
	"glm-4.6",
	"glm-4.7",
	"glm-4.7-free",
	"glm-5",
	"glm-5-free",
	"gpt-5",
	"gpt-5-codex",
	"gpt-5-nano",
	"gpt-5.1",
	"gpt-5.1-codex",
	"gpt-5.1-codex-max",
	"gpt-5.1-codex-mini",
	"gpt-5.2",
	"gpt-5.2-codex",
	"gpt-5.3-codex",
	"gpt-5.3-codex-spark",
	"gpt-5.4",
	"gpt-5.4-pro",
	"grok-code",
	"kimi-k2",
	"kimi-k2-thinking",
	"kimi-k2.5",
	"kimi-k2.5-free",
	"minimax-m2.1",
	"minimax-m2.1-free",
	"minimax-m2.5",
	"minimax-m2.5-free",
	"qwen3-coder",
	"trinity-large-preview-free",
}

var modelsByID = map[string]model.LLMModelInfo{
	"big-pickle": {
		ID:               "big-pickle",
		Name:             "Big Pickle",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-5-haiku": {
		ID:               "claude-3-5-haiku",
		Name:             "Claude Haiku 3.5",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  8192,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-haiku-4-5": {
		ID:               "claude-haiku-4-5",
		Name:             "Claude Haiku 4.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-1": {
		ID:               "claude-opus-4-1",
		Name:             "Claude Opus 4.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-5": {
		ID:               "claude-opus-4-5",
		Name:             "Claude Opus 4.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-6": {
		ID:               "claude-opus-4-6",
		Name:             "Claude Opus 4.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4": {
		ID:               "claude-sonnet-4",
		Name:             "Claude Sonnet 4",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-5": {
		ID:               "claude-sonnet-4-5",
		Name:             "Claude Sonnet 4.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-6": {
		ID:               "claude-sonnet-4-6",
		Name:             "Claude Sonnet 4.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gemini-3-flash": {
		ID:               "gemini-3-flash",
		Name:             "Gemini 3 Flash",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gemini-3-pro": {
		ID:               "gemini-3-pro",
		Name:             "Gemini 3 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gemini-3.1-pro": {
		ID:               "gemini-3.1-pro",
		Name:             "Gemini 3.1 Pro Preview",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-4.6": {
		ID:               "glm-4.6",
		Name:             "GLM-4.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-4.7": {
		ID:               "glm-4.7",
		Name:             "GLM-4.7",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-4.7-free": {
		ID:               "glm-4.7-free",
		Name:             "GLM-4.7 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5": {
		ID:               "glm-5",
		Name:             "GLM-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5-free": {
		ID:               "glm-5-free",
		Name:             "GLM-5 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5": {
		ID:               "gpt-5",
		Name:             "GPT-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-codex": {
		ID:               "gpt-5-codex",
		Name:             "GPT-5 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-nano": {
		ID:               "gpt-5-nano",
		Name:             "GPT-5 Nano",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1": {
		ID:               "gpt-5.1",
		Name:             "GPT-5.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex": {
		ID:               "gpt-5.1-codex",
		Name:             "GPT-5.1 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-max": {
		ID:               "gpt-5.1-codex-max",
		Name:             "GPT-5.1 Codex Max",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-mini": {
		ID:               "gpt-5.1-codex-mini",
		Name:             "GPT-5.1 Codex Mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2": {
		ID:               "gpt-5.2",
		Name:             "GPT-5.2",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2-codex": {
		ID:               "gpt-5.2-codex",
		Name:             "GPT-5.2 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex": {
		ID:               "gpt-5.3-codex",
		Name:             "GPT-5.3 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex-spark": {
		ID:               "gpt-5.3-codex-spark",
		Name:             "GPT-5.3 Codex Spark",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4": {
		ID:               "gpt-5.4",
		Name:             "GPT-5.4",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4-pro": {
		ID:               "gpt-5.4-pro",
		Name:             "GPT-5.4 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"grok-code": {
		ID:               "grok-code",
		Name:             "Grok Code Fast 1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    256000,
		MaxOutputTokens:  256000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2": {
		ID:               "kimi-k2",
		Name:             "Kimi K2",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  262144,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2-thinking": {
		ID:               "kimi-k2-thinking",
		Name:             "Kimi K2 Thinking",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  262144,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.5": {
		ID:               "kimi-k2.5",
		Name:             "Kimi K2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.5-free": {
		ID:               "kimi-k2.5-free",
		Name:             "Kimi K2.5 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  262144,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.1": {
		ID:               "minimax-m2.1",
		Name:             "MiniMax M2.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.1-free": {
		ID:               "minimax-m2.1-free",
		Name:             "MiniMax M2.1 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.5": {
		ID:               "minimax-m2.5",
		Name:             "MiniMax M2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.5-free": {
		ID:               "minimax-m2.5-free",
		Name:             "MiniMax M2.5 Free",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3-coder": {
		ID:               "qwen3-coder",
		Name:             "Qwen3 Coder",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"trinity-large-preview-free": {
		ID:               "trinity-large-preview-free",
		Name:             "Trinity Large Preview",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    131072,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

// IsSupportedModel returns true if model ID exists in the Zen catalog.
func IsSupportedModel(modelID string) bool {
	_, ok := modelsByID[modelID]
	return ok
}

// ModelByID returns model metadata when present.
func ModelByID(modelID string) (model.LLMModelInfo, bool) {
	v, ok := modelsByID[modelID]
	return v, ok
}

// SupportedModelIDs returns all known Zen model IDs.
func SupportedModelIDs() []string {
	ids := make([]string, len(modelIDs))
	copy(ids, modelIDs)
	return ids
}
