// Code generated by pkg/llm/internal/cmd/genmodels. DO NOT EDIT.
// Source: https://models.dev/api.json

package opencodego

import "github.com/slok/gosimov/pkg/model"

type modelAPIFormat string

const (
	modelAPIFormatOpenAICompatible modelAPIFormat = "openai-compatible"
	modelAPIFormatAnthropic        modelAPIFormat = "anthropic"
)

const (
	ModelGlm5       = "glm-5"
	ModelKimiK25    = "kimi-k2.5"
	ModelMinimaxM25 = "minimax-m2.5"
)

var modelIDs = []string{
	"glm-5",
	"kimi-k2.5",
	"minimax-m2.5",
}

var modelsByID = map[string]model.LLMModelInfo{
	"glm-5": {
		ID:               "glm-5",
		Name:             "GLM-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.5": {
		ID:               "kimi-k2.5",
		Name:             "Kimi K2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.5": {
		ID:               "minimax-m2.5",
		Name:             "MiniMax M2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

var modelFormatsByID = map[string]modelAPIFormat{
	"glm-5":        modelAPIFormatOpenAICompatible,
	"kimi-k2.5":    modelAPIFormatOpenAICompatible,
	"minimax-m2.5": modelAPIFormatAnthropic,
}

// IsSupportedModel returns true if model ID exists in the OpenCode Go catalog.
func IsSupportedModel(modelID string) bool {
	_, ok := modelsByID[modelID]
	return ok
}

// ModelByID returns model metadata when present.
func ModelByID(modelID string) (model.LLMModelInfo, bool) {
	v, ok := modelsByID[modelID]
	return v, ok
}

// ModelFormatByID returns API format metadata when present.
func ModelFormatByID(modelID string) (modelAPIFormat, bool) {
	v, ok := modelFormatsByID[modelID]
	return v, ok
}

// SupportedModelIDs returns all known OpenCode Go model IDs.
func SupportedModelIDs() []string {
	ids := make([]string, len(modelIDs))
	copy(ids, modelIDs)
	return ids
}
