// Code generated by pkg/llm/internal/cmd/genmodels. DO NOT EDIT.
// Source: https://models.dev/api.json

package opencodego

import "github.com/slok/gosimov/pkg/model"

const (
	ModelDeepseekV4Flash = "deepseek-v4-flash"
	ModelDeepseekV4Pro   = "deepseek-v4-pro"
	ModelGlm5            = "glm-5"
	ModelGlm51           = "glm-5.1"
	ModelKimiK25         = "kimi-k2.5"
	ModelKimiK26         = "kimi-k2.6"
	ModelMimoV2Omni      = "mimo-v2-omni"
	ModelMimoV2Pro       = "mimo-v2-pro"
	ModelMimoV25         = "mimo-v2.5"
	ModelMimoV25Pro      = "mimo-v2.5-pro"
	ModelMinimaxM27      = "minimax-m2.7"
	ModelQwen35Plus      = "qwen3.5-plus"
	ModelQwen36Plus      = "qwen3.6-plus"
)

var modelIDs = []string{
	"deepseek-v4-flash",
	"deepseek-v4-pro",
	"glm-5",
	"glm-5.1",
	"kimi-k2.5",
	"kimi-k2.6",
	"mimo-v2-omni",
	"mimo-v2-pro",
	"mimo-v2.5",
	"mimo-v2.5-pro",
	"minimax-m2.7",
	"qwen3.5-plus",
	"qwen3.6-plus",
}

var modelsByID = map[string]model.LLMModelInfo{
	"deepseek-v4-flash": {
		ID:               "deepseek-v4-flash",
		Name:             "DeepSeek V4 Flash",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  384000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"deepseek-v4-pro": {
		ID:               "deepseek-v4-pro",
		Name:             "DeepSeek V4 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  384000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5": {
		ID:               "glm-5",
		Name:             "GLM-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    202752,
		MaxOutputTokens:  32768,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"glm-5.1": {
		ID:               "glm-5.1",
		Name:             "GLM-5.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    202752,
		MaxOutputTokens:  32768,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.5": {
		ID:               "kimi-k2.5",
		Name:             "Kimi K2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"kimi-k2.6": {
		ID:               "kimi-k2.6",
		Name:             "Kimi K2.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2-omni": {
		ID:               "mimo-v2-omni",
		Name:             "MiMo V2 Omni",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2-pro": {
		ID:               "mimo-v2-pro",
		Name:             "MiMo V2 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2.5": {
		ID:               "mimo-v2.5",
		Name:             "MiMo V2.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1000000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityAudio, model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"mimo-v2.5-pro": {
		ID:               "mimo-v2.5-pro",
		Name:             "MiMo V2.5 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1048576,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"minimax-m2.7": {
		ID:               "minimax-m2.7",
		Name:             "MiniMax M2.7",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    204800,
		MaxOutputTokens:  131072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3.5-plus": {
		ID:               "qwen3.5-plus",
		Name:             "Qwen3.5 Plus",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"qwen3.6-plus": {
		ID:               "qwen3.6-plus",
		Name:             "Qwen3.6 Plus",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    262144,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText, model.LLMModelInputModalityVideo},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

// IsSupportedModel returns true if model ID exists in the OpenCode Go catalog.
func IsSupportedModel(modelID string) bool {
	_, ok := modelsByID[modelID]
	return ok
}

// ModelByID returns model metadata when present.
func ModelByID(modelID string) (model.LLMModelInfo, bool) {
	v, ok := modelsByID[modelID]
	return v, ok
}

// SupportedModelIDs returns all known OpenCode Go model IDs.
func SupportedModelIDs() []string {
	ids := make([]string, len(modelIDs))
	copy(ids, modelIDs)
	return ids
}
