// Code generated by pkg/llm/internal/cmd/genmodels. DO NOT EDIT.
// Source: https://models.dev/api.json

package anthropic

import "github.com/slok/gosimov/pkg/model"

const (
	ModelClaude35Haiku20241022  = "claude-3-5-haiku-20241022"
	ModelClaude35HaikuLatest    = "claude-3-5-haiku-latest"
	ModelClaude35Sonnet20240620 = "claude-3-5-sonnet-20240620"
	ModelClaude35Sonnet20241022 = "claude-3-5-sonnet-20241022"
	ModelClaude37Sonnet20250219 = "claude-3-7-sonnet-20250219"
	ModelClaude37SonnetLatest   = "claude-3-7-sonnet-latest"
	ModelClaude3Haiku20240307   = "claude-3-haiku-20240307"
	ModelClaude3Opus20240229    = "claude-3-opus-20240229"
	ModelClaude3Sonnet20240229  = "claude-3-sonnet-20240229"
	ModelClaudeHaiku45          = "claude-haiku-4-5"
	ModelClaudeHaiku4520251001  = "claude-haiku-4-5-20251001"
	ModelClaudeOpus40           = "claude-opus-4-0"
	ModelClaudeOpus41           = "claude-opus-4-1"
	ModelClaudeOpus4120250805   = "claude-opus-4-1-20250805"
	ModelClaudeOpus420250514    = "claude-opus-4-20250514"
	ModelClaudeOpus45           = "claude-opus-4-5"
	ModelClaudeOpus4520251101   = "claude-opus-4-5-20251101"
	ModelClaudeOpus46           = "claude-opus-4-6"
	ModelClaudeSonnet40         = "claude-sonnet-4-0"
	ModelClaudeSonnet420250514  = "claude-sonnet-4-20250514"
	ModelClaudeSonnet45         = "claude-sonnet-4-5"
	ModelClaudeSonnet4520250929 = "claude-sonnet-4-5-20250929"
	ModelClaudeSonnet46         = "claude-sonnet-4-6"
)

var modelIDs = []string{
	"claude-3-5-haiku-20241022",
	"claude-3-5-haiku-latest",
	"claude-3-5-sonnet-20240620",
	"claude-3-5-sonnet-20241022",
	"claude-3-7-sonnet-20250219",
	"claude-3-7-sonnet-latest",
	"claude-3-haiku-20240307",
	"claude-3-opus-20240229",
	"claude-3-sonnet-20240229",
	"claude-haiku-4-5",
	"claude-haiku-4-5-20251001",
	"claude-opus-4-0",
	"claude-opus-4-1",
	"claude-opus-4-1-20250805",
	"claude-opus-4-20250514",
	"claude-opus-4-5",
	"claude-opus-4-5-20251101",
	"claude-opus-4-6",
	"claude-sonnet-4-0",
	"claude-sonnet-4-20250514",
	"claude-sonnet-4-5",
	"claude-sonnet-4-5-20250929",
	"claude-sonnet-4-6",
}

var modelsByID = map[string]model.LLMModelInfo{
	"claude-3-5-haiku-20241022": {
		ID:               "claude-3-5-haiku-20241022",
		Name:             "Claude Haiku 3.5",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  8192,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-5-haiku-latest": {
		ID:               "claude-3-5-haiku-latest",
		Name:             "Claude Haiku 3.5 (latest)",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  8192,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-5-sonnet-20240620": {
		ID:               "claude-3-5-sonnet-20240620",
		Name:             "Claude Sonnet 3.5",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  8192,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-5-sonnet-20241022": {
		ID:               "claude-3-5-sonnet-20241022",
		Name:             "Claude Sonnet 3.5 v2",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  8192,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-7-sonnet-20250219": {
		ID:               "claude-3-7-sonnet-20250219",
		Name:             "Claude Sonnet 3.7",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-7-sonnet-latest": {
		ID:               "claude-3-7-sonnet-latest",
		Name:             "Claude Sonnet 3.7 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-haiku-20240307": {
		ID:               "claude-3-haiku-20240307",
		Name:             "Claude Haiku 3",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  4096,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-opus-20240229": {
		ID:               "claude-3-opus-20240229",
		Name:             "Claude Opus 3",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  4096,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-3-sonnet-20240229": {
		ID:               "claude-3-sonnet-20240229",
		Name:             "Claude Sonnet 3",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  4096,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-haiku-4-5": {
		ID:               "claude-haiku-4-5",
		Name:             "Claude Haiku 4.5 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-haiku-4-5-20251001": {
		ID:               "claude-haiku-4-5-20251001",
		Name:             "Claude Haiku 4.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-0": {
		ID:               "claude-opus-4-0",
		Name:             "Claude Opus 4 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-1": {
		ID:               "claude-opus-4-1",
		Name:             "Claude Opus 4.1 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-1-20250805": {
		ID:               "claude-opus-4-1-20250805",
		Name:             "Claude Opus 4.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-20250514": {
		ID:               "claude-opus-4-20250514",
		Name:             "Claude Opus 4",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-5": {
		ID:               "claude-opus-4-5",
		Name:             "Claude Opus 4.5 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-5-20251101": {
		ID:               "claude-opus-4-5-20251101",
		Name:             "Claude Opus 4.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-opus-4-6": {
		ID:               "claude-opus-4-6",
		Name:             "Claude Opus 4.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-0": {
		ID:               "claude-sonnet-4-0",
		Name:             "Claude Sonnet 4 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-20250514": {
		ID:               "claude-sonnet-4-20250514",
		Name:             "Claude Sonnet 4",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-5": {
		ID:               "claude-sonnet-4-5",
		Name:             "Claude Sonnet 4.5 (latest)",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-5-20250929": {
		ID:               "claude-sonnet-4-5-20250929",
		Name:             "Claude Sonnet 4.5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"claude-sonnet-4-6": {
		ID:               "claude-sonnet-4-6",
		Name:             "Claude Sonnet 4.6",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  64000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

// IsSupportedModel returns true if model ID exists in the Anthropic catalog.
func IsSupportedModel(modelID string) bool {
	_, ok := modelsByID[modelID]
	return ok
}

// ModelByID returns model metadata when present.
func ModelByID(modelID string) (model.LLMModelInfo, bool) {
	v, ok := modelsByID[modelID]
	return v, ok
}

// SupportedModelIDs returns all known Anthropic model IDs.
func SupportedModelIDs() []string {
	ids := make([]string, len(modelIDs))
	copy(ids, modelIDs)
	return ids
}
