// Code generated by pkg/llm/internal/cmd/genmodels. DO NOT EDIT.
// Source: https://models.dev/api.json

package openai

import "github.com/slok/gosimov/pkg/model"

const (
	ModelCodexMiniLatest     = "codex-mini-latest"
	ModelGpt35Turbo          = "gpt-3.5-turbo"
	ModelGpt4                = "gpt-4"
	ModelGpt4Turbo           = "gpt-4-turbo"
	ModelGpt41               = "gpt-4.1"
	ModelGpt41Mini           = "gpt-4.1-mini"
	ModelGpt41Nano           = "gpt-4.1-nano"
	ModelGpt4o               = "gpt-4o"
	ModelGpt4o20240513       = "gpt-4o-2024-05-13"
	ModelGpt4o20240806       = "gpt-4o-2024-08-06"
	ModelGpt4o20241120       = "gpt-4o-2024-11-20"
	ModelGpt4oMini           = "gpt-4o-mini"
	ModelGpt5                = "gpt-5"
	ModelGpt5ChatLatest      = "gpt-5-chat-latest"
	ModelGpt5Codex           = "gpt-5-codex"
	ModelGpt5Mini            = "gpt-5-mini"
	ModelGpt5Nano            = "gpt-5-nano"
	ModelGpt5Pro             = "gpt-5-pro"
	ModelGpt51               = "gpt-5.1"
	ModelGpt51ChatLatest     = "gpt-5.1-chat-latest"
	ModelGpt51Codex          = "gpt-5.1-codex"
	ModelGpt51CodexMax       = "gpt-5.1-codex-max"
	ModelGpt51CodexMini      = "gpt-5.1-codex-mini"
	ModelGpt52               = "gpt-5.2"
	ModelGpt52ChatLatest     = "gpt-5.2-chat-latest"
	ModelGpt52Codex          = "gpt-5.2-codex"
	ModelGpt52Pro            = "gpt-5.2-pro"
	ModelGpt53Codex          = "gpt-5.3-codex"
	ModelGpt53CodexSpark     = "gpt-5.3-codex-spark"
	ModelGpt54               = "gpt-5.4"
	ModelGpt54Pro            = "gpt-5.4-pro"
	ModelO1                  = "o1"
	ModelO1Mini              = "o1-mini"
	ModelO1Preview           = "o1-preview"
	ModelO1Pro               = "o1-pro"
	ModelO3                  = "o3"
	ModelO3DeepResearch      = "o3-deep-research"
	ModelO3Mini              = "o3-mini"
	ModelO3Pro               = "o3-pro"
	ModelO4Mini              = "o4-mini"
	ModelO4MiniDeepResearch  = "o4-mini-deep-research"
	ModelTextEmbedding3Large = "text-embedding-3-large"
	ModelTextEmbedding3Small = "text-embedding-3-small"
	ModelTextEmbeddingAda002 = "text-embedding-ada-002"
)

var openAIModelIDs = []string{
	"codex-mini-latest",
	"gpt-3.5-turbo",
	"gpt-4",
	"gpt-4-turbo",
	"gpt-4.1",
	"gpt-4.1-mini",
	"gpt-4.1-nano",
	"gpt-4o",
	"gpt-4o-2024-05-13",
	"gpt-4o-2024-08-06",
	"gpt-4o-2024-11-20",
	"gpt-4o-mini",
	"gpt-5",
	"gpt-5-chat-latest",
	"gpt-5-codex",
	"gpt-5-mini",
	"gpt-5-nano",
	"gpt-5-pro",
	"gpt-5.1",
	"gpt-5.1-chat-latest",
	"gpt-5.1-codex",
	"gpt-5.1-codex-max",
	"gpt-5.1-codex-mini",
	"gpt-5.2",
	"gpt-5.2-chat-latest",
	"gpt-5.2-codex",
	"gpt-5.2-pro",
	"gpt-5.3-codex",
	"gpt-5.3-codex-spark",
	"gpt-5.4",
	"gpt-5.4-pro",
	"o1",
	"o1-mini",
	"o1-preview",
	"o1-pro",
	"o3",
	"o3-deep-research",
	"o3-mini",
	"o3-pro",
	"o4-mini",
	"o4-mini-deep-research",
	"text-embedding-3-large",
	"text-embedding-3-small",
	"text-embedding-ada-002",
}

var openAIModelsByID = map[string]model.LLMModelInfo{
	"codex-mini-latest": {
		ID:               "codex-mini-latest",
		Name:             "Codex Mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-3.5-turbo": {
		ID:               "gpt-3.5-turbo",
		Name:             "GPT-3.5-turbo",
		Reasoning:        false,
		ToolCall:         false,
		ContextWindow:    16385,
		MaxOutputTokens:  4096,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4": {
		ID:               "gpt-4",
		Name:             "GPT-4",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    8192,
		MaxOutputTokens:  8192,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4-turbo": {
		ID:               "gpt-4-turbo",
		Name:             "GPT-4 Turbo",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  4096,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4.1": {
		ID:               "gpt-4.1",
		Name:             "GPT-4.1",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    1047576,
		MaxOutputTokens:  32768,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4.1-mini": {
		ID:               "gpt-4.1-mini",
		Name:             "GPT-4.1 mini",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    1047576,
		MaxOutputTokens:  32768,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4.1-nano": {
		ID:               "gpt-4.1-nano",
		Name:             "GPT-4.1 nano",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    1047576,
		MaxOutputTokens:  32768,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4o": {
		ID:               "gpt-4o",
		Name:             "GPT-4o",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  16384,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4o-2024-05-13": {
		ID:               "gpt-4o-2024-05-13",
		Name:             "GPT-4o (2024-05-13)",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  4096,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4o-2024-08-06": {
		ID:               "gpt-4o-2024-08-06",
		Name:             "GPT-4o (2024-08-06)",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  16384,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4o-2024-11-20": {
		ID:               "gpt-4o-2024-11-20",
		Name:             "GPT-4o (2024-11-20)",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  16384,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-4o-mini": {
		ID:               "gpt-4o-mini",
		Name:             "GPT-4o mini",
		Reasoning:        false,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  16384,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5": {
		ID:               "gpt-5",
		Name:             "GPT-5",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-chat-latest": {
		ID:               "gpt-5-chat-latest",
		Name:             "GPT-5 Chat (latest)",
		Reasoning:        true,
		ToolCall:         false,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-codex": {
		ID:               "gpt-5-codex",
		Name:             "GPT-5-Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-mini": {
		ID:               "gpt-5-mini",
		Name:             "GPT-5 Mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-nano": {
		ID:               "gpt-5-nano",
		Name:             "GPT-5 Nano",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-pro": {
		ID:               "gpt-5-pro",
		Name:             "GPT-5 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  272000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1": {
		ID:               "gpt-5.1",
		Name:             "GPT-5.1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-chat-latest": {
		ID:               "gpt-5.1-chat-latest",
		Name:             "GPT-5.1 Chat",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  16384,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex": {
		ID:               "gpt-5.1-codex",
		Name:             "GPT-5.1 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-max": {
		ID:               "gpt-5.1-codex-max",
		Name:             "GPT-5.1 Codex Max",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-mini": {
		ID:               "gpt-5.1-codex-mini",
		Name:             "GPT-5.1 Codex mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2": {
		ID:               "gpt-5.2",
		Name:             "GPT-5.2",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2-chat-latest": {
		ID:               "gpt-5.2-chat-latest",
		Name:             "GPT-5.2 Chat",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  16384,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2-codex": {
		ID:               "gpt-5.2-codex",
		Name:             "GPT-5.2 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2-pro": {
		ID:               "gpt-5.2-pro",
		Name:             "GPT-5.2 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex": {
		ID:               "gpt-5.3-codex",
		Name:             "GPT-5.3 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex-spark": {
		ID:               "gpt-5.3-codex-spark",
		Name:             "GPT-5.3 Codex Spark",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4": {
		ID:               "gpt-5.4",
		Name:             "GPT-5.4",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.4-pro": {
		ID:               "gpt-5.4-pro",
		Name:             "GPT-5.4 Pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    1050000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o1": {
		ID:               "o1",
		Name:             "o1",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o1-mini": {
		ID:               "o1-mini",
		Name:             "o1-mini",
		Reasoning:        true,
		ToolCall:         false,
		ContextWindow:    128000,
		MaxOutputTokens:  65536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o1-preview": {
		ID:               "o1-preview",
		Name:             "o1-preview",
		Reasoning:        true,
		ToolCall:         false,
		ContextWindow:    128000,
		MaxOutputTokens:  32768,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o1-pro": {
		ID:               "o1-pro",
		Name:             "o1-pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o3": {
		ID:               "o3",
		Name:             "o3",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o3-deep-research": {
		ID:               "o3-deep-research",
		Name:             "o3-deep-research",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o3-mini": {
		ID:               "o3-mini",
		Name:             "o3-mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o3-pro": {
		ID:               "o3-pro",
		Name:             "o3-pro",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o4-mini": {
		ID:               "o4-mini",
		Name:             "o4-mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"o4-mini-deep-research": {
		ID:               "o4-mini-deep-research",
		Name:             "o4-mini-deep-research",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"text-embedding-3-large": {
		ID:               "text-embedding-3-large",
		Name:             "text-embedding-3-large",
		Reasoning:        false,
		ToolCall:         false,
		ContextWindow:    8191,
		MaxOutputTokens:  3072,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"text-embedding-3-small": {
		ID:               "text-embedding-3-small",
		Name:             "text-embedding-3-small",
		Reasoning:        false,
		ToolCall:         false,
		ContextWindow:    8191,
		MaxOutputTokens:  1536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"text-embedding-ada-002": {
		ID:               "text-embedding-ada-002",
		Name:             "text-embedding-ada-002",
		Reasoning:        false,
		ToolCall:         false,
		ContextWindow:    8192,
		MaxOutputTokens:  1536,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

var chatGPTModelIDs = []string{
	"codex-mini-latest",
	"gpt-5-codex",
	"gpt-5.1-codex",
	"gpt-5.1-codex-max",
	"gpt-5.1-codex-mini",
	"gpt-5.2-codex",
	"gpt-5.3-codex",
	"gpt-5.3-codex-spark",
}

var chatGPTModelsByID = map[string]model.LLMModelInfo{
	"codex-mini-latest": {
		ID:               "codex-mini-latest",
		Name:             "Codex Mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    200000,
		MaxOutputTokens:  100000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5-codex": {
		ID:               "gpt-5-codex",
		Name:             "GPT-5-Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex": {
		ID:               "gpt-5.1-codex",
		Name:             "GPT-5.1 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-max": {
		ID:               "gpt-5.1-codex-max",
		Name:             "GPT-5.1 Codex Max",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.1-codex-mini": {
		ID:               "gpt-5.1-codex-mini",
		Name:             "GPT-5.1 Codex mini",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.2-codex": {
		ID:               "gpt-5.2-codex",
		Name:             "GPT-5.2 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex": {
		ID:               "gpt-5.3-codex",
		Name:             "GPT-5.3 Codex",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    400000,
		MaxOutputTokens:  128000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
	"gpt-5.3-codex-spark": {
		ID:               "gpt-5.3-codex-spark",
		Name:             "GPT-5.3 Codex Spark",
		Reasoning:        true,
		ToolCall:         true,
		ContextWindow:    128000,
		MaxOutputTokens:  32000,
		InputModalities:  []model.LLMModelInputModality{model.LLMModelInputModalityImage, model.LLMModelInputModalityPDF, model.LLMModelInputModalityText},
		OutputModalities: []model.LLMModelOutputModality{model.LLMModelOutputModalityText},
	},
}

// IsSupportedOpenAIModel returns true if model ID exists in the OpenAI catalog.
func IsSupportedOpenAIModel(modelID string) bool {
	_, ok := openAIModelsByID[modelID]
	return ok
}

// IsSupportedChatGPTModel returns true if model ID exists in the ChatGPT catalog.
func IsSupportedChatGPTModel(modelID string) bool {
	_, ok := chatGPTModelsByID[modelID]
	return ok
}

// OpenAIModelInfo returns OpenAI model metadata when present.
func OpenAIModelInfo(modelID string) (model.LLMModelInfo, bool) {
	v, ok := openAIModelsByID[modelID]
	return v, ok
}

// ChatGPTModelInfo returns ChatGPT model metadata when present.
func ChatGPTModelInfo(modelID string) (model.LLMModelInfo, bool) {
	v, ok := chatGPTModelsByID[modelID]
	return v, ok
}

// SupportedOpenAIModelIDs returns all known OpenAI model IDs.
func SupportedOpenAIModelIDs() []string {
	ids := make([]string, len(openAIModelIDs))
	copy(ids, openAIModelIDs)
	return ids
}

// SupportedChatGPTModelIDs returns all known ChatGPT model IDs.
func SupportedChatGPTModelIDs() []string {
	ids := make([]string, len(chatGPTModelIDs))
	copy(ids, chatGPTModelIDs)
	return ids
}
